/**
 * Copy the platform's skill vocabulary into the functions build.
 *
 * Imported listings tag themselves with skills that match what members
 * actually pick on their profiles, so the daily sync needs the same 300-term
 * list the app uses. Firebase only uploads the `functions/` directory, so the
 * list cannot be imported across the repo — it is generated instead, from
 * app/lib/skills.ts, as part of `npm run build`. Never edit the output by hand.
 */
const fs = require("fs");
const path = require("path");

const SOURCE = path.join(__dirname, "..", "..", "app", "lib", "skills.ts");
const OUT = path.join(__dirname, "..", "src", "jobs", "skills.ts");

function main() {
  if (!fs.existsSync(SOURCE)) {
    // Deploying from a checkout that only has functions/ — keep whatever was
    // generated last time rather than failing the build.
    if (fs.existsSync(OUT)) {
      console.log("sync-skills: app/lib/skills.ts not found, keeping existing list.");
      return;
    }
    throw new Error(`sync-skills: cannot find ${SOURCE} and no generated list exists.`);
  }

  const src = fs.readFileSync(SOURCE, "utf8");
  const body = src.slice(src.indexOf("["), src.lastIndexOf("]"));
  const skills = [...new Set([...body.matchAll(/"([^"]{2,40})"/g)].map((m) => m[1]))];
  if (skills.length < 100) {
    throw new Error(`sync-skills: only parsed ${skills.length} skills — refusing to write.`);
  }

  const out = `// GENERATED by functions/scripts/sync-skills.js from app/lib/skills.ts.
// Do not edit — run \`npm run build\` in functions/ to regenerate.
export const SKILL_VOCAB: string[] = ${JSON.stringify(skills, null, 2)};
`;

  fs.mkdirSync(path.dirname(OUT), { recursive: true });
  fs.writeFileSync(OUT, out);
  console.log(`sync-skills: wrote ${skills.length} skills to src/jobs/skills.ts`);
}

main();
